// Curated list of Nepal treks — mix of famous and hidden gems
export interface CuratedTrek {
  name: string;
  slug: string;
  difficulty: "easy" | "moderate" | "strenuous" | "extreme";
  durationDays: number;
  maxElevationM: number;
  startPoint: string;
  endPoint: string;
  distanceKm: number;
  region: string;
  category: "famous" | "hidden_gem" | "remote";
  permitRequired: boolean;
  permitCostUsd: number;
  wikipediaTitle?: string;
  summary: string;
}

export const CURATED_TREKS: CuratedTrek[] = [
  // ─── Famous treks ──────────────────────────────────────
  {
    name: "Everest Base Camp Trek",
    slug: "everest-base-camp",
    difficulty: "strenuous",
    durationDays: 14,
    maxElevationM: 5644,
    startPoint: "Lukla",
    endPoint: "Lukla",
    distanceKm: 130,
    region: "Khumbu",
    category: "famous",
    permitRequired: true,
    permitCostUsd: 50,
    wikipediaTitle: "Mount Everest base camps",
    summary: "The classic trek to the foot of the world's highest mountain through Sherpa villages and high-altitude valleys.",
  },
  {
    name: "Annapurna Circuit",
    slug: "annapurna-circuit",
    difficulty: "strenuous",
    durationDays: 15,
    maxElevationM: 5416,
    startPoint: "Besisahar",
    endPoint: "Pokhara",
    distanceKm: 230,
    region: "Annapurna",
    category: "famous",
    permitRequired: true,
    permitCostUsd: 50,
    wikipediaTitle: "Annapurna Circuit",
    summary: "A legendary loop crossing the Thorong La Pass at 5,416m through diverse landscapes and cultures.",
  },
  {
    name: "Langtang Valley Trek",
    slug: "langtang-valley",
    difficulty: "moderate",
    durationDays: 8,
    maxElevationM: 4984,
    startPoint: "Syabrubesi",
    endPoint: "Syabrubesi",
    distanceKm: 65,
    region: "Langtang",
    category: "famous",
    permitRequired: true,
    permitCostUsd: 35,
    wikipediaTitle: "Langtang National Park",
    summary: "A quiet valley trek close to Kathmandu through Tamang villages and pristine forests.",
  },
  {
    name: "Gokyo Lakes Trek",
    slug: "gokyo-lakes",
    difficulty: "strenuous",
    durationDays: 12,
    maxElevationM: 5357,
    startPoint: "Lukla",
    endPoint: "Lukla",
    distanceKm: 92,
    region: "Khumbu",
    category: "famous",
    permitRequired: true,
    permitCostUsd: 50,
    wikipediaTitle: "Gokyo Lakes",
    summary: "Turquoise high-altitude lakes and the Gokyo Ri viewpoint with 4 of the world's 6 highest peaks.",
  },
  {
    name: "Three Passes Trek",
    slug: "three-passes",
    difficulty: "extreme",
    durationDays: 20,
    maxElevationM: 5535,
    startPoint: "Lukla",
    endPoint: "Lukla",
    distanceKm: 165,
    region: "Khumbu",
    category: "famous",
    permitRequired: true,
    permitCostUsd: 50,
    summary: "The ultimate Khumbu adventure crossing three high passes: Kongma La, Cho La, and Renjo La.",
  },
  {
    name: "Ghorepani Poon Hill Trek",
    slug: "ghorepani-poon-hill",
    difficulty: "easy",
    durationDays: 5,
    maxElevationM: 3210,
    startPoint: "Nayapul",
    endPoint: "Nayapul",
    distanceKm: 32,
    region: "Annapurna",
    category: "famous",
    permitRequired: true,
    permitCostUsd: 30,
    summary: "Nepal's most accessible sunrise — panoramic Annapurna and Dhaulagiri views from Poon Hill.",
  },
  {
    name: "Mardi Himal Trek",
    slug: "mardi-himal",
    difficulty: "moderate",
    durationDays: 6,
    maxElevationM: 4500,
    startPoint: "Kande",
    endPoint: "Phedi",
    distanceKm: 42,
    region: "Annapurna",
    category: "famous",
    permitRequired: true,
    permitCostUsd: 30,
    summary: "A relatively new trek with rhododendron forests and a stunning High Camp viewpoint.",
  },
  {
    name: "Upper Mustang Trek",
    slug: "upper-mustang",
    difficulty: "moderate",
    durationDays: 12,
    maxElevationM: 4200,
    startPoint: "Jomsom",
    endPoint: "Jomsom",
    distanceKm: 95,
    region: "Mustang",
    category: "famous",
    permitRequired: true,
    permitCostUsd: 500,
    wikipediaTitle: "Mustang District, Nepal",
    summary: "The forbidden kingdom — Tibetan-influenced culture, cave monasteries, and Mars-like landscapes.",
  },

  // ─── Hidden gems ───────────────────────────────────────
  {
    name: "Khopra Ridge Trek",
    slug: "khopra-ridge",
    difficulty: "moderate",
    durationDays: 7,
    maxElevationM: 3660,
    startPoint: "Nayapul",
    endPoint: "Nayapul",
    distanceKm: 55,
    region: "Annapurna",
    category: "hidden_gem",
    permitRequired: true,
    permitCostUsd: 30,
    summary: "An off-the-beaten-path Annapurna alternative with epic Dhaulagiri sunrise views.",
  },
  {
    name: "Mohare Danda Trek",
    slug: "mohare-danda",
    difficulty: "easy",
    durationDays: 6,
    maxElevationM: 3300,
    startPoint: "Galeshwor",
    endPoint: "Beni",
    distanceKm: 48,
    region: "Annapurna",
    category: "hidden_gem",
    permitRequired: true,
    permitCostUsd: 30,
    summary: "Community-run lodges, no crowds, and a quieter alternative to Poon Hill.",
  },
  {
    name: "Tsum Valley Trek",
    slug: "tsum-valley",
    difficulty: "moderate",
    durationDays: 14,
    maxElevationM: 3700,
    startPoint: "Soti Khola",
    endPoint: "Soti Khola",
    distanceKm: 95,
    region: "Manaslu",
    category: "hidden_gem",
    permitRequired: true,
    permitCostUsd: 70,
    summary: "A hidden Tibetan valley closed to outsiders until 2008 — ancient monasteries and untouched culture.",
  },
  {
    name: "Pikey Peak Trek",
    slug: "pikey-peak",
    difficulty: "easy",
    durationDays: 5,
    maxElevationM: 4065,
    startPoint: "Jiri",
    endPoint: "Phaplu",
    distanceKm: 35,
    region: "Solukhumbu",
    category: "hidden_gem",
    permitRequired: false,
    permitCostUsd: 0,
    summary: "Sir Edmund Hillary's favorite Everest view — accessible without altitude sickness risk.",
  },
  {
    name: "Tamang Heritage Trail",
    slug: "tamang-heritage-trail",
    difficulty: "easy",
    durationDays: 7,
    maxElevationM: 3165,
    startPoint: "Syabrubesi",
    endPoint: "Syabrubesi",
    distanceKm: 55,
    region: "Langtang",
    category: "hidden_gem",
    permitRequired: true,
    permitCostUsd: 35,
    summary: "Cultural trek through Tamang villages with hot springs, monasteries, and Tibetan-influenced cuisine.",
  },
  {
    name: "Ruby Valley Trek",
    slug: "ruby-valley",
    difficulty: "moderate",
    durationDays: 9,
    maxElevationM: 3842,
    startPoint: "Syabrubesi",
    endPoint: "Borang",
    distanceKm: 75,
    region: "Ganesh Himal",
    category: "hidden_gem",
    permitRequired: true,
    permitCostUsd: 35,
    summary: "An untouched valley between Manaslu and Langtang with ruby mines and Tamang culture.",
  },
  {
    name: "Helambu Trek",
    slug: "helambu",
    difficulty: "easy",
    durationDays: 6,
    maxElevationM: 3650,
    startPoint: "Sundarijal",
    endPoint: "Melamchi",
    distanceKm: 55,
    region: "Bagmati",
    category: "hidden_gem",
    permitRequired: true,
    permitCostUsd: 30,
    summary: "Closest trek to Kathmandu — Sherpa and Tamang villages without altitude challenges.",
  },
  {
    name: "Naar Phu Valley Trek",
    slug: "naar-phu-valley",
    difficulty: "strenuous",
    durationDays: 12,
    maxElevationM: 5320,
    startPoint: "Koto",
    endPoint: "Manang",
    distanceKm: 90,
    region: "Annapurna",
    category: "hidden_gem",
    permitRequired: true,
    permitCostUsd: 90,
    summary: "Hidden Tibetan villages in restricted area — wild yaks, ancient gompas, and Kang La pass.",
  },

  // ─── Remote/lesser-known ───────────────────────────────
  {
    name: "Kanchenjunga Base Camp Trek",
    slug: "kanchenjunga-base-camp",
    difficulty: "strenuous",
    durationDays: 22,
    maxElevationM: 5143,
    startPoint: "Taplejung",
    endPoint: "Taplejung",
    distanceKm: 220,
    region: "Eastern Nepal",
    category: "remote",
    permitRequired: true,
    permitCostUsd: 20,
    wikipediaTitle: "Kangchenjunga",
    summary: "Trek to the world's 3rd highest peak through one of Nepal's last true wildernesses.",
  },
  {
    name: "Upper Dolpo Trek",
    slug: "upper-dolpo",
    difficulty: "extreme",
    durationDays: 22,
    maxElevationM: 5360,
    startPoint: "Juphal",
    endPoint: "Juphal",
    distanceKm: 200,
    region: "Dolpo",
    category: "remote",
    permitRequired: true,
    permitCostUsd: 500,
    wikipediaTitle: "Dolpa District",
    summary: "Phoksundo Lake, ancient Bon monasteries, and the trans-Himalayan desert in Nepal's wildest district.",
  },
  {
    name: "Khaptad Circuit",
    slug: "khaptad-circuit",
    difficulty: "moderate",
    durationDays: 8,
    maxElevationM: 3300,
    startPoint: "Silgadhi",
    endPoint: "Silgadhi",
    distanceKm: 60,
    region: "Far West",
    category: "remote",
    permitRequired: false,
    permitCostUsd: 0,
    summary: "Sacred rolling meadows in Nepal's least-visited national park — pilgrims and pristine grasslands.",
  },
  {
    name: "Api Himal Base Camp",
    slug: "api-himal-base-camp",
    difficulty: "strenuous",
    durationDays: 12,
    maxElevationM: 4200,
    startPoint: "Darchula",
    endPoint: "Darchula",
    distanceKm: 90,
    region: "Far West",
    category: "remote",
    permitRequired: true,
    permitCostUsd: 90,
    summary: "Nepal's least-trekked corner with views of Api Peak and indigenous Bhotiya culture.",
  },
];
